# Generated by Django 5.1.6 on 2025-02-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clasificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('sinopsis', models.CharField(max_length=535)),
                ('reparto', models.CharField(max_length=150)),
                ('director', models.IntegerField()),
                ('fecha_estreno', models.DateField()),
                ('trailer', models.CharField(max_length=150)),
                ('duracion', models.IntegerField()),
            ],
            options={
                'db_table': 'pelicula',
                'managed': False,
            },
        ),
    ]
