# Generated by Django 5.1.6 on 2025-02-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'managed': True},
        ),
    ]
