# Generated by Django 5.1.6 on 2025-02-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'managed': False},
        ),
    ]
